export const ACTION_TYPE = {
  // Bookmarks
  ADD_BOOKMARK: "ADD_BOOKMARK",
  EDIT_BOOKMARK: "EDIT_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  SET_BOOKMARKS: "SET_BOOKMARKS",
  //Collections
  ADD_COLLECTION: "ADD_COLLECTION",
  EDIT_COLLECTION: "EDIT_COLLECTION",
  UPDATE_COLLECTION: "UPDATE_COLLECTION",
  SET_COLLECTIONS: "SET_COLLECTIONS",
  //Collections Order
  SET_COLLECTIONS_ORDER: "SET_COLLECTIONS_ORDER",
};
