export const ACTION_TYPE = {
  // Bookmarks
  ADD_BOOKMARK: "ADD_BOOKMARK",
  EDIT_BOOKMARK: "EDIT_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  REMOVE_BOOKMARKS: "REMOVE_BOOKMARKS",
  SET_BOOKMARKS: "SET_BOOKMARKS",
  //Collections
  ADD_COLLECTION: "ADD_COLLECTION",
  EDIT_COLLECTION: "EDIT_COLLECTION",
  UPDATE_COLLECTION: "UPDATE_COLLECTION",
  REMOVE_COLLECTION: "REMOVE_COLLECTION",
  REMOVE_BOOKMARK_FROM_COLLECTION: "REMOVE_BOOKMARK_FROM_COLLECTION",
  TOGGLE_COLLECTION: "TOGGLE_COLLECTION",
  SET_COLLECTIONS: "SET_COLLECTIONS",
  //Collections Order
  SET_COLLECTIONS_ORDER: "SET_COLLECTIONS_ORDER",
  REMOVE_COLLECTION_FROM_ORDER: "REMOVE_COLLECTION_FROM_ORDER",
  UPDATE_COLLECTIONS_ORDER: "UPDATE_COLLECTIONS_ORDER",
  ADD_NEW_COLLECTION_TO_ORDER: "ADD_NEW_COLLECTION_TO_ORDER"
};

export const ACTION_TYPE_STORAGE_KEY_MAP = {
  // Bookmarks
  ADD_BOOKMARK: "bookmarks",
  EDIT_BOOKMARK: "bookmarks",
  REMOVE_BOOKMARK: "bookmarks",
  REMOVE_BOOKMARKS: "bookmarks",
  SET_BOOKMARKS: "bookmarks",
  //Collections
  ADD_COLLECTION: "collections",
  EDIT_COLLECTION: "collections",
  UPDATE_COLLECTION: "collections",
  REMOVE_COLLECTION: "collections",
  REMOVE_BOOKMARK_FROM_COLLECTION: "collections",
  TOGGLE_COLLECTION: "collections",
  SET_COLLECTIONS: "collections",
  //Collections Order
  SET_COLLECTIONS_ORDER: "collectionsOrder",
  REMOVE_COLLECTION_FROM_ORDER: "collectionsOrder",
  UPDATE_COLLECTIONS_ORDER: "collectionsOrder",
  ADD_NEW_COLLECTION_TO_ORDER: "collectionsOrder",
}