export const ACTION_TYPE = {
  // Bookmarks
  ADD_BOOKMARK: "ADD_BOOKMARK",
  EDIT_BOOKMARK: "EDIT_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  REMOVE_BOOKMARKS: "REMOVE_BOOKMARKS",
  SET_BOOKMARKS: "SET_BOOKMARKS",
  //Collections
  ADD_COLLECTION: "ADD_COLLECTION",
  EDIT_COLLECTION: "EDIT_COLLECTION",
  UPDATE_COLLECTION: "UPDATE_COLLECTION",
  REMOVE_COLLECTION: "REMOVE_COLLECTION",
  REMOVE_BOOKMARK_FROM_COLLECTION: "REMOVE_BOOKMARK_FROM_COLLECTION",
  TOGGLE_COLLECTION: "TOGGLE_COLLECTION",
  SET_COLLECTIONS: "SET_COLLECTIONS",
  //Collections Order
  SET_COLLECTIONS_ORDER: "SET_COLLECTIONS_ORDER",
  REMOVE_COLLECTION_FROM_ORDER: "REMOVE_COLLECTION_FROM_ORDER",
};
